name: planner
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  crypto: ^3.0.0
  cupertino_icons: ^1.0.8 # add cupertino icons to to application
  table_calendar: ^3.2.0
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  syncfusion_flutter_calendar: 28.2.11
  idb_shim: ^2.0.0+2 #for Indexed DB web app support
  uuid: ^4.4.2 #generate unique id numbers in api friendly format

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true